name: Test build

on:
  pull_request:
    branches:
      - main
    
jobs:
  main:
    name: Build and run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          go test ./...

      - name: Check if ortotris binary builds
        run: |
          cd cmd/ortotris
          go build .

      - name: Check if lettersnake binary builds
        run: |
          cd cmd/lettersnake
          go build .
